In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


### Introduction to tensors
## Creating tensors

Tensors creating with torch.tensor() -> https://docs.pytorch.org/docs/stable/tensors.html

Scalars & Vectors are undercase, Matrices and Tensors are uppercase.

In [ ]:
# scalar - no dimensions
scalar = torch.tensor(7)
scalar

7

In [ ]:
# num dimensions
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
# There exists 1 3x3 shaped tensor
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random #'s, look at data -> update random #'s -> look at data -> update random numbers`


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.8612, 0.6798, 0.1963, 0.7302],
         [0.3423, 0.0123, 0.9379, 0.3688],
         [0.3019, 0.7011, 0.3584, 0.7491]],

        [[0.9707, 0.3840, 0.1212, 0.3496],
         [0.4301, 0.4878, 0.2971, 0.4886],
         [0.8858, 0.0013, 0.7738, 0.6620]]])

In [ ]:
# Create random tensor w/ similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Most common errors:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensor not on right device

In [ ]:
float_32_sensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # type of datatype
                               device=None, # What device the tensor is on
                               requires_grad=False) # Whether or not to track gradients w/ this tensor operations
print(float_32_sensor)
float_32_sensor

tensor([3., 6., 9.])


tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_sensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor


tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting tensor attributes

1. use `tensor.dtype` to get datatype
2. use `tensor.shape` to get shape
3. use `tensor.device` to get device




In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0539, 0.2446, 0.5809, 0.8561],
        [0.7474, 0.1185, 0.6385, 0.9365],
        [0.8039, 0.4681, 0.3161, 0.4608]])

In [ ]:
print(f"{some_tensor.dtype}, {some_tensor.shape}, {some_tensor.device}")

torch.float32, torch.Size([3, 4]), cpu


### Tensor operations

Addition, Subtraction, Multiplication (element-wise), Division, Matrix Multiplication

In [ ]:
# Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# PyTorch operations
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Matrix multiplication
rand_tensor = torch.rand(1, 3)
rand_tensor_2 = torch.rand(1, 3)
print(rand_tensor, rand_tensor_2)
torch.matmul(rand_tensor, rand_tensor_2.T)

tensor([[0.8432, 0.0540, 0.3007]]) tensor([[0.0986, 0.3250, 0.4643]])


tensor([[0.2403]])

### One of the biggest errors: Shape errors
Two main rules:
1. Inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

r1, c1 * r2, c2 = r1, c2 where c1 and r2 must be equal
* `[1,2] @ [2, 1] = [1, 1]`

In [ ]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
print(tensor_a)
print(tensor_b.T)
torch.mm(tensor_a, tensor_b.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor aggregation (min, max, mean, sum, etc.)

In [ ]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Min: {x.min()}")
print(f"Max: {torch.max(x)}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Min: 0
Max: 90


In [ ]:
# torch.mean requires a tensor of float32

torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

### Finding the positional min and max

In [ ]:
print(x)
print(torch.argmin(x))
print(torch.argmax(x))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(9)


## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshape - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped in a certain way)

In [ ]:
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensors shares the same memory as the original)
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Squeeze - torch.squeeze(), removes all single dimensions from a target tensor
x_reshaped = x.reshape(1, 9)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
print(f"New tensor: {x_reshaped.squeeze()}")
print(f"New shape: {x_reshaped.squeeze().shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [ ]:
# Unsequeeze - torch.unsqueeze(), adds a single dimension to a target tensor at a specific dimension
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
x_reshaped = x_reshaped.unsqueeze(dim=0)
print(f"New tensor: {x_reshaped}")
print(f"New shape: {x_reshaped.shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])
New shape: torch.Size([1, 1, 9])


In [ ]:
# Permute - torch.permute, rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # height, width, color channels
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape
print(x[0])
print(x[0][0])
print(x[0][0][0])
print(x[:, :, 1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor([[2, 5, 8]])


###PyTorch Tensors and NumPy
* PyTorch tensor -> NumPy = `torch.from_numpy(ndarray)`
* NumPy -> PyTorch tensor = `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

array = np.arange(0, 11.0)
tensor = torch.from_numpy(array)
tensor, tensor.dtype # NumPy default type is float64

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        dtype=torch.float64),
 torch.float64)

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

How a NN learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce randomness in NN and PyTorch comes the concept of a **random seed**.

In [ ]:
import torch

rand_tensor_a = torch.rand(3, 4)
rand_tensor_b = torch.rand(3, 4)

print(rand_tensor_a)
print(rand_tensor_b)
print(rand_tensor_a == rand_tensor_b)

tensor([[0.3920, 0.0256, 0.7274, 0.1181],
        [0.0353, 0.8101, 0.2484, 0.2168],
        [0.9544, 0.2862, 0.9137, 0.1409]])
tensor([[0.3286, 0.4313, 0.0063, 0.2358],
        [0.9425, 0.3811, 0.9921, 0.1077],
        [0.0566, 0.1644, 0.2368, 0.7309]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch
# setting a seed generally works for one block of code at a time
torch.manual_seed(42)
rand_tensor_a = torch.rand(3, 4)

torch.manual_seed(42)
rand_tensor_b = torch.rand(3, 4)

print(rand_tensor_a)
print(rand_tensor_b)
print(rand_tensor_a == rand_tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
